version: "3.7"

services:
  app:
    image: anatolykatz/mymetrics:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      - FLASK_APP:/app/main.py
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: .
        target: /app

#    command:
#      - flask run

networks:
  backend:
