version: "3.8"

services:
  app:
    image: anatolykatz/mymetrics:1.1.2
    container_name: mymetrics
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      - FLASK_APP:/app/main.py
    ports:
      - "8000:8080"
    volumes:
      - type: bind
        source: .
        target: /app

  prometheus:
    image: bitnami/prometheus:2.55.1
    container_name: prometheus
    ports:
      - "9090:9090" # Expose Prometheus on localhost:9090
    volumes:
      - prometheus_data:/bitnami/prometheus # Persist Prometheus data
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro # Custom configuration file
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes # Example environment variable for Bitnami's configuration
    networks:
      - backend

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    ports:
      - "3000:3000" # Expose Grafana on localhost:3000
    environment:
      - GF_SECURITY_ADMIN_USER=tolyankatz # Default admin username
      - GF_SECURITY_ADMIN_PASSWORD=tolyan@007 # Default admin password
      - GF_SERVER_HTTP_PORT=3000 # Grafana HTTP port
    volumes:
      - grafana_data:/var/lib/grafana # Persist Grafana data
    networks:
      - backend


networks:
  backend:

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
