apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: app-mymetrics
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 1s

    scrape_configs:
      - job_name: "flask_app"
        static_configs:
          - targets: ["mymetrics-service:8080"]
