apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: app-mymetrics
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: bitnami/prometheus:2.55.1
        env:
          - name: ALLOW_ANONYMOUS_LOGIN
            value: "yes"
        ports:
        - containerPort: 9090
